general.import = [
"alacritty-theme/themes/gruvbox_material_hard_dark.toml",
]

[window]
opacity = 0.95 # not used because of niri
decorations = "Buttonless"
padding = { x = 8, y = 8 }

[scrolling]
history = 11000

[font]
normal = { family = "MesloLGLDZ Nerd Font", style = "Regular" }
size = 14.00

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true
