general.import = [
"alacritty-theme/themes/gruvbox_material_hard_dark.toml",
]

[window]
#opacity = 0.92 # not used because of niri
decorations = "None"

[scrolling]
history = 11000

[font]
normal = { family = "monospace", style = "regular" }
size = 14.00

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true


